---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
        - name: rocketchat
          image: registry.rocket.chat/rocketchat/rocket.chat:6.4.8
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
            - name: ROOT_URL
              value: http://rocketchat.local
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat
spec:
  selector:
    app: rocketchat
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocketchat-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: rocketchat.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rocketchat
                port:
                  number: 3000
